---
- hosts: localhost
  connection: local

  vars_files:
    - default.config.yml
    - vars/extra-packages.yml
    - vars/python.yml
    - vars/rust.yml
    - vars/vscode.yml
    - vars/rust-packages.yml

  pre_tasks:
  - name: Update APT Repositories
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present

  tasks:
    - name: Install extra apt Packages
      ansible.builtin.import_tasks: tasks/extra-packages.yml
      tags: ['extra_packages']

    - name: Install Dotfiles
      ansible.builtin.import_tasks: tasks/dotfiles.yml
      tags: ['dotfiles']
      when: install_dotfiles

    - name: Install Tmux
      ansible.builtin.import_tasks: tasks/tmux.yml
      tags: ['tmux']
      when: install_tmux

    - name: Configure Git
      ansible.builtin.import_tasks: tasks/git.yml
      tags: ['git']
      when: configure_git

    - name: Install Pip Packages
      ansible.builtin.import_tasks: tasks/python.yml
      tags: ['python']
      when: install_python

    - name: Install VS Code
      ansible.builtin.import_tasks: tasks/vscode.yml
      tags: ['vscode']
      when: install_vscode

    - name: Install Picocom
      ansible.builtin.import_tasks: tasks/picocom.yml
      tags: ['picocom']
      when: install_picocom

    - name: Install Neovim
      ansible.builtin.import_tasks: tasks/neovim.yml
      tags: ['neovim']
      when: install_neovim

    - name: Install Rust
      ansible.builtin.import_tasks: tasks/rust.yml
      tags: ['rust', 'rust_packages']
      when: install_rust

    - name: Install Rust
      ansible.builtin.import_tasks: tasks/rust-packages.yml
      tags: ['rust_packages']
      when: install_rust

    - name: Install Docker
      ansible.builtin.import_tasks: tasks/docker.yml
      tags: ['docker']
      when: install_docker

    - name: Install VLC 
      ansible.builtin.import_tasks: tasks/vlc.yml
      tags: ['vlc']
      when: install_vlc

    - name: Install LibreOffice
      ansible.builtin.import_tasks: tasks/libreoffice.yml
      tags: ['libreoffice']
      when: install_libreoffice

    - name: Install SQLite3
      ansible.builtin.import_tasks: tasks/sqlite3.yml
      tags: ['sqlite3']
      when: install_sqlite3

    - name: Install Dracula Theme
      ansible.builtin.import_tasks: tasks/dracula-theme.yml
      tags: ['dracula_theme']
      when: install_dracula_theme

    - name: Install Spotify
      ansible.builtin.import_tasks: tasks/spotify.yml
      tags: ['spotify']
      when: install_spotify
